### PR TITLE
Eliminate wall wextra warnings

### PR DESCRIPTION
**Pull request by ijnek**
Hi, thanks for the development of this library!
It has been proving useful in the development of a ROS project [Nao Soccer Sim](https://github.com/ijnek/naosoccer_sim).
I have eliminated all warnings when compiled with -Wall -Wextra for my project, and thought it may be useful for others also.

I have committed "per warning", so you can see exactly which changes were required against which warnings.

### CODE REVIEW

**Comment by ijnek** [comment]
Hi @BitPuffin , I understand that this repository may not be actively developed, but I'd be interested in hearing your feedback on this PR.

**Comment by BitPuffin** [comment]
Hello @ijnek thanks for your contribution. I have not deliberately ignored your PR. But rather it seems like github didn't email me until you @ mentioned me. (Could also be possible that I got an email but it got buried).

I'm very excited to hear about usage in your project. If you have feedback to report for future developments I am open to hearing them. It's true that I haven't actively developed the library but I have been tossing around the idea of making some improvements. Although I have also been wanting to avoid feature creep (hence the very low volume maintainence mode).

In either case I will have a look at the changes you've made and get them merged once I've reviewed them. Have a nice day!

**Review by BitPuffin — COMMENTED** [review]
The 0ba8e81e20cf3b8 commit I have some issues with. It's true that it will get rid of the warning but it changes the intent of the code. 

At least when I look at the code with these additions it's not clear to me that getting to the added return statements is supposed to ever happen. The way the code was written originally relies on the switch statement doing exhaustive checks of the SexpValueKind enum values. And adding a return statement afterwards makes it seem like it is there to take care of the case when the value is not one of the two (which should never happen).

Hypothetically if I added a symbol type (which I've thought about, due to some idiosyncrasies of the library now) and I forgot to add another case clause in some place, having these return statements would make it harder to interpret if it was intended to only check for those two or not. I'm not sure if the compiler would help me out with exhaustiveness checking though. But I think it warns you if you don't check everything without having a default clause.

Anyway that's my thoughts on this commit. What do you think about it?

**Comment by BitPuffin** [comment]
Everything else pretty much looks great.

The f4b61a7d37df90d9fc39829f commit I'm uncertain if `unsigned` is the best choice. I would probably use size_t but I'm not convinced that it makes the most sense. Also since the general style in this project is to use auto very much maybe there is some initializer like `0u` that we should use instead. I'm a bit rusty though with the specifics.

For 70c07847e16a34b3581286d9e9a4e48dac0bf976 it looks to me like I had made a mistake (I forget to put in break more often than I'd like). But did you run the tests and make sure it does not introduce bugs? Just in case it was intentionally not breaking. If it is supposed to be intentional I think we should have some comment saying that we want the fall through. But looking at the code I can't see why we would want it to fall through. But just wanna make sure :)

**Comment by ijnek** [comment]
> The [0ba8e81](https://github.com/BitPuffin/sexpresso/commit/0ba8e81e20cf3b84a8fccd8c3364d039db4bab8a) commit I have some issues with. It's true that it will get rid of the warning but it changes the intent of the code.

I agree. I would suggest throwing a invalid_argument exception OR print to std::cerr ("error: Should never reach here") and return 0, in the default case. I don't know which you would prefer. I prefer throwing an invalid_argument exception, as the only way to fix the issue if it arises should be to modify the code.

**Comment by ijnek** [comment]
> The [f4b61a7](https://github.com/BitPuffin/sexpresso/commit/f4b61a7d37df90d9fc39829f5eba481eaa5ecc02) commit I'm uncertain if `unsigned` is the best choice. I would probably use size_t but I'm not convinced that it makes the most sense. Also since the general style in this project is to use auto very much maybe there is some initializer like `0u` that we should use instead. I'm a bit rusty though with the specifics.

Modified in 45a3b04 to go with 0u, per your suggestion.

> For [70c0784](https://github.com/BitPuffin/sexpresso/commit/70c07847e16a34b3581286d9e9a4e48dac0bf976) it looks to me like I had made a mistake (I forget to put in break more often than I'd like). But did you run the tests and make sure it does not introduce bugs? Just in case it was intentionally not breaking. If it is supposed to be intentional I think we should have some comment saying that we want the fall through. But looking at the code I can't see why we would want it to fall through. But just wanna make sure :)

Just ran both tests, `test-sexpresso-std.sh` and `test-sexpresso.sh`, and all tests pass :+1:

**Comment by BitPuffin** [comment]
Hello!

Thank you for the fixes. Regarding the exception, I want the library to be smoothly usable for people who choose to disable exceptions, so I'd rather have it print to cerr.

As for the other stuff it's looking good!

By the way, since the library is public domain (CC0), would you be okay with waiving your copyright to the changes?
I don't think that with relatively small changes it's a big deal but I think it's better to be on the safe side!

**Comment by ijnek** [comment]
> Thank you for the fixes. Regarding the exception, I want the library to be smoothly usable for people who choose to disable exceptions, so I'd rather have it print to cerr.

Done!

> By the way, since the library is public domain (CC0), would you be okay with waiving your copyright to the changes?

I'm not too familiar with CC0, but I've added `// Modified: Kenji Brameld 2021` to the top of `sexpresso.cpp` and `sexpresso.hpp`. Tell me if that's not how you wanted it and I can fix it up!

**Comment by BitPuffin** [comment]
> I'm not too familiar with CC0, but I've added // Modified: Kenji Brameld 2021 to the top of sexpresso.cpp and sexpresso.hpp.Tell me if that's not how you wanted it and I can fix it up!

It's different from what I meant. CC0 is a public domain declaration, but you generally speaking by default have copyright on anything you make. So you have to explicitly give up copyrights in order to put something in the public domain. Again I'm not sure how hairy it gets with relatively small changes, but still want to be on the safe side.

So in practice, I suggest that we  make a CONTRIBUTORS file which contains a statement like.

```
Sexpresso is available in the public domain through the CC0 license (see COPYING.txt for details, or https://creativecommons.org/publicdomain/zero/1.0/legalcode).
The following people have made contributions to sexpresso and consented to dedicating their changes to the public domain:

Kenji Brameld, 2021
```

And then other people could make a commit with their "signature". Since they make the commit themselves it is probably good enough of a "signature" for our purposes. At least I hope so! :)

**Comment by ijnek** [comment]
@BitPuffin
Should be good now, I've added my signature, and wrote a Contributing section in README.org

**Comment by ijnek** [comment]
@BitPuffin in case you've forgotten about this.

**Comment by BitPuffin** [comment]
Hey!

Sorry I hadn't forgotten I just had a hard time getting around to it. I checked the changes one more time and merged it now. Contribution very much appreciated! Sorry for being kind of slow on the ball. Good luck with the soccer ball project!

**Pull request merged**
